# Cleaning Data - Midterm - ANSWERS
## The Midterm is due by midnight on MM/DD/YYYY.  The python skills you learned you can use to clean a dataset.  If you get a job in Data science you will need to clean the data.  If you have any questions, please email me through Canvas or joellen.green@fresnocitycollege.edu.

### One the basic data science tasks is cleaning data.  In this assignment you will learn to clean a data set.  This is the midterm for the DS 10 Introduction to Data Science course.

You will use the chronic kidney disease dataset from the University of California, Irvine data science repositary. You will run the code cell below to use the Table functions to help you out.

In [1]:
import numpy as np
from datascience import *

# These lines set up graphing capabilities.
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import pandas as pd

## In this assignment you will clean a dataset using the Python tools learn thus far.
<br>
Attribute Information:<br>
We use the following representation to collect the dataset<br>
- age - age in years (numerical)<br>
- bp - blood pressure in mm/Hg (numerical)<br>
- sg - specific gravity sg (1.005, 1.010, 1.020, 1.025) (nominal)<br>
- al - albumin (0, 1, 2, 3, 4, 5) (ordinal)<br>
- su - sugar (0, 1, 2, 3, 4, 5) (ordinal)<br>
- rbc - red blood cells (normal, abnormal)(nominal)<br>
- pc - pus cell (normal, abnormal) (nominal)<br>
- pcc - pus cell clumps (present, notpresent) (nominal)<br>
- ba - bacteria (present, notpresent) (nominal)<br>
- bgr - blood glucose random mgs/dl (numerical)<br>
- bu - blood urea mgs/dl (numerical)<br>
- sc - serum creatinine mgs/dl (numerical)<br>
- sod - sodium mEq/L (numerical)<br>
- pot - potassium mEq/L (numerical)<br>
- hemo - hemoglobin gms (numerical)<br>
- pcv - packed cell volume (numerical)<br>
- wc - white blood cell count (cells/cumm) (numerical)<br>
- rc - red blood cell count millions/cmm (numerical)<br>
- htn - hypertension (yes, no) (nominal)<br>
- dm - diabetes mellitus (yes, no) (nominal)<br>
- cad - coronary artery disease (yes, no) (nominal)<br>
- appet - appetite (good, poor) (nominal)<br>
- pe - pedal edema (yes, no) (nominal)<br>
- ane - anemia (yes, no) (nominal)<br>
- classification - class (ckd, notckd) (nominal)<br>
<br>
**Knowing the data types is very important**<br>
- (nominal) - label with no numerical order<br>
- (ordinal) - label with numberical order<br>
- (interval) - numerical with no real 0 (0 means nothing)<br>
- (ratio) - numerical with a real 0 (0 means nothing)<br>

In [25]:
filename = 'kidney_disease.csv'
kidney_disease = Table.read_table(filename)
kidney_disease

id   | 'age' | 'bp' | 'sg'  | 'al' | 'su' | 'rbc'    | 'pc'     | 'pcc'      | 'ba'       | 'bgr' | 'bu' | 'sc' | 'sod' | 'pot' | 'hemo' | 'pcv' | 'wbcc' | 'rbcc' | 'htn' | 'dm' | 'cad' | 'appet' | 'pe' | 'ane' | 'class'
1    | 48    | 80   | 1.020 | 1    | 0    | ?        | normal   | notpresent | notpresent | 121   | 36   | 1.2  | ?     | ?     | 15.4   | 44    | 7800   | 5.2    | yes   | yes  | no    | good    | no   | no    | ckd
2    | 7     | 50   | 1.020 | 4    | 0    | ?        | normal   | notpresent | notpresent | ?     | 18   | 0.8  | ?     | ?     | 11.3   | 38    | 6000   | ?      | no    | no   | no    | good    | no   | no    | ckd
3    | 62    | 80   | 1.010 | 2    | 3    | normal   | normal   | notpresent | notpresent | 423   | 53   | 1.8  | ?     | ?     | 9.6    | 31    | 7500   | ?      | no    | yes  | no    | poor    | no   | yes   | ckd
4    | 48    | 70   | 1.005 | 4    | 0    | normal   | abnormal | present    | notpresent | 117   | 56   | 3.8  | 111   | 2.5   | 11.2   | 32    | 6700   | 3.9    | yes   | no   | no    | poor    | yes  | yes   | ckd
5    | 51    | 80   | 1.010 | 2    | 0    | normal   | normal   | notpresent | notpresent | 106   | 26   | 1.4  | ?     | ?     | 11.6   | 35    | 7300   | 4.6    | no    | no   | no    | good    | no   | no    | ckd
6    | 60    | 90   | 1.015 | 3    | 0    | ?        | ?        | notpresent | notpresent | 74    | 25   | 1.1  | 142   | 3.2   | 12.2   | 39    | 7800   | 4.4    | yes   | yes  | no    | good    | yes  | no    | ckd
7    | 68    | 70   | 1.010 | 0    | 0    | ?        | normal   | notpresent | notpresent | 100   | 54   | 24.0 | 104   | 4.0   | 12.4   | 36    | ?      | ?      | no    | no   | no    | good    | no   | no    | ckd
8    | 24    | ?    | 1.015 | 2    | 4    | normal   | abnormal | notpresent | notpresent | 410   | 31   | 1.1  | ?     | ?     | 12.4   | 44    | 6900   | 5      | no    | yes  | no    | good    | yes  | no    | ckd
9    | 52    | 100  | 1.015 | 3    | 0    | normal   | abnormal | present    | notpresent | 138   | 60   | 1.9  | ?     | ?     | 10.8   | 33    | 9600   | 4.0    | yes   | yes  | no    | good    | no   | yes   | ckd
10   | 53    | 90   | 1.020 | 2    | 0    | abnormal | abnormal | present    | notpresent | 70    | 107  | 7.2  | 114   | 3.7   | 9.5    | 29    | 12100  | 3.7    | yes   | yes  | no    | poor    | no   | yes   | ckd
... (390 rows omitted)

# Change the labels to the full name<br>

In [26]:
kidney_diseae = kidney_disease.relabel(make_array("'age'", "'bp'", "'sg'", "'class'"),
  make_array("age", "blood pressure", "specific gravity", "class"))
kidney_disease

id   | age  | blood pressure | specific gravity | 'al' | 'su' | 'rbc'    | 'pc'     | 'pcc'      | 'ba'       | 'bgr' | 'bu' | 'sc' | 'sod' | 'pot' | 'hemo' | 'pcv' | 'wbcc' | 'rbcc' | 'htn' | 'dm' | 'cad' | 'appet' | 'pe' | 'ane' | class
1    | 48   | 80             | 1.020            | 1    | 0    | ?        | normal   | notpresent | notpresent | 121   | 36   | 1.2  | ?     | ?     | 15.4   | 44    | 7800   | 5.2    | yes   | yes  | no    | good    | no   | no    | ckd
2    | 7    | 50             | 1.020            | 4    | 0    | ?        | normal   | notpresent | notpresent | ?     | 18   | 0.8  | ?     | ?     | 11.3   | 38    | 6000   | ?      | no    | no   | no    | good    | no   | no    | ckd
3    | 62   | 80             | 1.010            | 2    | 3    | normal   | normal   | notpresent | notpresent | 423   | 53   | 1.8  | ?     | ?     | 9.6    | 31    | 7500   | ?      | no    | yes  | no    | poor    | no   | yes   | ckd
4    | 48   | 70             | 1.005            | 4    | 0    | normal   | abnormal | present    | notpresent | 117   | 56   | 3.8  | 111   | 2.5   | 11.2   | 32    | 6700   | 3.9    | yes   | no   | no    | poor    | yes  | yes   | ckd
5    | 51   | 80             | 1.010            | 2    | 0    | normal   | normal   | notpresent | notpresent | 106   | 26   | 1.4  | ?     | ?     | 11.6   | 35    | 7300   | 4.6    | no    | no   | no    | good    | no   | no    | ckd
6    | 60   | 90             | 1.015            | 3    | 0    | ?        | ?        | notpresent | notpresent | 74    | 25   | 1.1  | 142   | 3.2   | 12.2   | 39    | 7800   | 4.4    | yes   | yes  | no    | good    | yes  | no    | ckd
7    | 68   | 70             | 1.010            | 0    | 0    | ?        | normal   | notpresent | notpresent | 100   | 54   | 24.0 | 104   | 4.0   | 12.4   | 36    | ?      | ?      | no    | no   | no    | good    | no   | no    | ckd
8    | 24   | ?              | 1.015            | 2    | 4    | normal   | abnormal | notpresent | notpresent | 410   | 31   | 1.1  | ?     | ?     | 12.4   | 44    | 6900   | 5      | no    | yes  | no    | good    | yes  | no    | ckd
9    | 52   | 100            | 1.015            | 3    | 0    | normal   | abnormal | present    | notpresent | 138   | 60   | 1.9  | ?     | ?     | 10.8   | 33    | 9600   | 4.0    | yes   | yes  | no    | good    | no   | yes   | ckd
10   | 53   | 90             | 1.020            | 2    | 0    | abnormal | abnormal | present    | notpresent | 70    | 107  | 7.2  | 114   | 3.7   | 9.5    | 29    | 12100  | 3.7    | yes   | yes  | no    | poor    | no   | yes   | ckd
... (390 rows omitted)

### Question 1: Create an array called old_names of variables names from al to ane.  Then created an array called new_names.  Finally use the relabel method to change the variable names.

In [27]:
old_names =make_array("'al'","'su'","'rbc'","'pc'","'pcc'","'ba'","'bgr'","'bu'","'sc'","'sod'",
                      "'pot'","'hemo'","'pcv'","'wbcc'","'rbcc'","'htn'","'dm'","'cad'","'appet'","'pe'","'ane'")
new_names = make_array("albumin", "sugar", "red blood cells", "pus cell", "pus cell clumps", "bacteria", 
                       "blood glucose random", "blood urea", "serum creatinine", "sodium", "potassium", "hemoglobin",
                      "packed cell volume", "white blood cell count", "red blood cell count", "hypertension",
                      "diabetes mellitus", "coronary artery disease", "appetite", "pedal edema", "anemia")


kidney_disease = kidney_disease.relabel(old_names, new_names)
kidney_disease

id   | age  | blood pressure | specific gravity | albumin | sugar | red blood cells | pus cell | pus cell clumps | bacteria   | blood glucose random | blood urea | serum creatinine | sodium | potassium | hemoglobin | packed cell volume | white blood cell count | red blood cell count | hypertension | diabetes mellitus | coronary artery disease | appetite | pedal edema | anemia | class
1    | 48   | 80             | 1.020            | 1       | 0     | ?               | normal   | notpresent      | notpresent | 121                  | 36         | 1.2              | ?      | ?         | 15.4       | 44                 | 7800                   | 5.2                  | yes          | yes               | no                      | good     | no          | no     | ckd
2    | 7    | 50             | 1.020            | 4       | 0     | ?               | normal   | notpresent      | notpresent | ?                    | 18         | 0.8              | ?      | ?         | 11.3       | 38                 | 6000                   | ?                    | no           | no                | no                      | good     | no          | no     | ckd
3    | 62   | 80             | 1.010            | 2       | 3     | normal          | normal   | notpresent      | notpresent | 423                  | 53         | 1.8              | ?      | ?         | 9.6        | 31                 | 7500                   | ?                    | no           | yes               | no                      | poor     | no          | yes    | ckd
4    | 48   | 70             | 1.005            | 4       | 0     | normal          | abnormal | present         | notpresent | 117                  | 56         | 3.8              | 111    | 2.5       | 11.2       | 32                 | 6700                   | 3.9                  | yes          | no                | no                      | poor     | yes         | yes    | ckd
5    | 51   | 80             | 1.010            | 2       | 0     | normal          | normal   | notpresent      | notpresent | 106                  | 26         | 1.4              | ?      | ?         | 11.6       | 35                 | 7300                   | 4.6                  | no           | no                | no                      | good     | no          | no     | ckd
6    | 60   | 90             | 1.015            | 3       | 0     | ?               | ?        | notpresent      | notpresent | 74                   | 25         | 1.1              | 142    | 3.2       | 12.2       | 39                 | 7800                   | 4.4                  | yes          | yes               | no                      | good     | yes         | no     | ckd
7    | 68   | 70             | 1.010            | 0       | 0     | ?               | normal   | notpresent      | notpresent | 100                  | 54         | 24.0             | 104    | 4.0       | 12.4       | 36                 | ?                      | ?                    | no           | no                | no                      | good     | no          | no     | ckd
8    | 24   | ?              | 1.015            | 2       | 4     | normal          | abnormal | notpresent      | notpresent | 410                  | 31         | 1.1              | ?      | ?         | 12.4       | 44                 | 6900                   | 5                    | no           | yes               | no                      | good     | yes         | no     | ckd
9    | 52   | 100            | 1.015            | 3       | 0     | normal          | abnormal | present         | notpresent | 138                  | 60         | 1.9              | ?      | ?         | 10.8       | 33                 | 9600                   | 4.0                  | yes          | yes               | no                      | good     | no          | yes    | ckd
10   | 53   | 90             | 1.020            | 2       | 0     | abnormal        | abnormal | present         | notpresent | 70                   | 107        | 7.2              | 114    | 3.7       | 9.5        | 29                 | 12100                  | 3.7                  | yes          | yes               | no                      | poor     | no          | yes    | ckd
... (390 rows omitted)

### To get additional information about the data we will convert the data to a Pandas dataframe show the first 50 records

In [28]:
chronic_kidney_disease = kidney_disease.to_df()  # pandas dataframe
chronic_kidney_disease[0:50]                     # show 50 lines of data

,id,age,blood pressure,specific gravity,albumin,sugar,red blood cells,pus cell,pus cell clumps,bacteria,...,packed cell volume,white blood cell count,red blood cell count,hypertension,diabetes mellitus,coronary artery disease,appetite,pedal edema,anemia,class
0,1,48,80,1.020,1,0,?,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,2,7,50,1.020,4,0,?,normal,notpresent,notpresent,...,38,6000,?,no,no,no,good,no,no,ckd
2,3,62,80,1.010,2,3,normal,normal,notpresent,notpresent,...,31,7500,?,no,yes,no,poor,no,yes,ckd
3,4,48,70,1.005,4,0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,5,51,80,1.010,2,0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
5,6,60,90,1.015,3,0,?,?,notpresent,notpresent,...,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,7,68,70,1.010,0,0,?,normal,notpresent,notpresent,...,36,?,?,no,no,no,good,no,no,ckd
7,8,24,?,1.015,2,4,normal,abnormal,notpresent,notpresent,...,44,6900,5,no,yes,no,good,yes,no,ckd
8,9,52,100,1.015,3,0,normal,abnormal,present,notpresent,...,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,10,53,90,1.020,2,0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
10,11,50,60,1.010,2,4,?,abnormal,present,notpresent,...,28,?,?,yes,yes,no,good,no,yes,ckd
11,12,63,70,1.010,3,0,abnormal,abnormal,present,notpresent,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
12,13,68,70,1.015,3,1,?,normal,present,notpresent,...,28,12200,3.4,yes,yes,yes,poor,yes,no,ckd
13,14,68,70,?,?,?,?,?,notpresent,notpresent,...,?,?,?,yes,yes,yes,poor,yes,no,ckd
14,15,68,80,1.010,3,2,normal,abnormal,present,present,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
15,16,40,80,1.015,3,0,?,normal,notpresent,notpresent,...,24,3800,2.8,yes,no,no,good,no,yes,ckd
16,17,47,70,1.015,2,0,?,normal,notpresent,notpresent,...,?,?,?,no,no,no,good,no,no,ckd
17,18,47,80,?,?,?,?,?,notpresent,notpresent,...,?,?,?,yes,no,no,poor,no,no,ckd
18,19,60,100,1.025,0,3,?,normal,notpresent,notpresent,...,37,11400,4.3,yes,yes,yes,good,no,no,ckd
19,20,62,60,1.015,1,0,?,abnormal,present,notpresent,...,30,5300,3.7,yes,no,yes,good,no,no,ckd
20,21,61,80,1.015,2,0,abnormal,abnormal,notpresent,notpresent,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
21,22,60,90,?,?,?,?,?,notpresent,notpresent,...,32,6200,3.6,yes,yes,yes,good,no,no,ckd
22,23,48,80,1.025,4,0,normal,abnormal,notpresent,notpresent,...,32,6900,3.4,yes,no,no,good,no,yes,ckd
23,24,21,70,1.010,0,0,?,normal,notpresent,notpresent,...,?,?,?,no,no,no,poor,no,yes,ckd
24,25,42,100,1.015,4,0,normal,abnormal,notpresent,present,...,39,8300,4.6,yes,no,no,poor,no,no,ckd
25,26,61,60,1.025,0,0,?,normal,notpresent,notpresent,...,29,8400,3.7,yes,yes,no,good,no,yes,ckd
26,27,75,80,1.015,0,0,?,normal,notpresent,notpresent,...,35,10300,4,yes,yes,no,poor,no,no,ckd
27,28,69,70,1.010,3,4,normal,abnormal,notpresent,notpresent,...,37,9600,4.1,yes,yes,yes,good,yes,no,ckd
28,29,75,70,?,1,3,?,?,notpresent,notpresent,...,?,?,?,no,yes,no,good,no,no,ckd
29,30,68,70,1.005,1,0,abnormal,abnormal,present,notpresent,...,38,?,?,no,no,yes,good,no,no,ckd
30,31,?,70,?,?,?,?,?,notpresent,notpresent,...,?,?,?,yes,yes,no,good,no,no,ckd
31,32,73,90,1.015,3,0,?,abnormal,present,notpresent,...,30,7800,4,no,no,no,poor,no,no,ckd
32,33,61,90,1.010,1,1,?,normal,notpresent,notpresent,...,34,9600,4.0,yes,yes,no,poor,no,no,ckd
33,34,60,100,1.020,2,0,abnormal,abnormal,notpresent,notpresent,...,29,?,?,yes,no,no,poor,no,no,ckd
34,35,70,70,1.010,1,0,normal,?,present,present,...,?,?,?,no,yes,no,poor,no,no,ckd
35,36,65,90,1.020,2,1,abnormal,normal,notpresent,notpresent,...,36,9800,4.9,yes,yes,no,poor,no,yes,ckd
36,37,76,70,1.015,1,0,normal,normal,notpresent,notpresent,...,32,?,?,yes,no,no,good,no,no,ckd
37,38,72,80,?,?,?,?,?,notpresent,notpresent,...,28,6900,2.5,yes,yes,no,poor,no,yes,ckd
38,39,69,80,1.020,3,0,abnormal,normal,notpresent,notpresent,...,?,?,?,yes,no,no,good,no,no,ckd
39,40,82,80,1.010,2,2,normal,?,notpresent,notpresent,...,40,9800,4.2,yes,yes,no,good,no,no,ckd
40,41,46,90,1.010,2,0,normal,abnormal,notpresent,notpresent,...,32,9100,4.1,yes,no,no,good,no,no,ckd
41,42,45,70,1.010,0,0,?,normal,notpresent,notpresent,...,?,?,?,no,no,no,good,yes,no,ckd
42,43,47,100,1.010,0,0,?,normal,notpresent,notpresent,...,33,9200,4.5,yes,no,no,good,no,yes,ckd
43,44,35,80,1.010,1,0,abnormal,?,notpresent,notpresent,...,24,7900,3.1,no,yes,no,good,no,no,ckd
44,45,54,80,1.010,3,0,abnormal,abnormal,notpresent,notpresent,...,28,?,?,yes,yes,no,poor,yes,no,ckd
45,46,54,80,1.020,3,0,?,abnormal,notpresent,notpresent,...,?,?,?,yes,yes,no,poor,yes,no,ckd
46,47,48,70,1.015,0,0,?,normal,notpresent,notpresent,...,37,6400,4.7,no,yes,no,good,no,no,ckd
47,48,11,80,1.010,3,0,?,normal,notpresent,notpresent,...,45,8600,?,no,no,no,good,no,no,ckd
48,49,73,70,1.005,0,0,normal,normal,notpresent,notpresent,...,29,18900,3.5,yes,yes,no,good,yes,no,ckd
49,50,60,70,1.010,2,0,normal,abnormal,present,notpresent,...,29,21600,3.5,yes,yes,no,poor,no,yes,ckd

# Question 2: Create an array of ordinal and nominal field
see the list above

In [29]:
string_names = make_array("albumin", "sugar", "red blood cells", "pus cell", 
                          "pus cell clumps","hypertension", "diabetes mellitus",
                          "coronary artery disease","appetite",
                         "pedal edema", "anemia", "class")

# Question 3: Create an array of numeric values that are integers
see the list above

In [7]:
integer_names = make_array("age", "blood pressure", "blood glucose random",
                           "blood urea", "sodium", "packed cell volume", 
                          "white blood cell count")

# Question 4: Create an array of numeric values that are decimal
see the list above

In [11]:
float_names = make_array("serum creatinine", "potassium", "hemoglobin")

# Make sure your arrays do not overlap 
## meaning the field name is in more than one array

# Note the data types are not as indicated in the table above
*Knowing the data types is very important**
- (nominal) - label with no numerical order
- (ordinal) - label with numberical order
- (interval) - numerical with no real 0 (0 means nothing)
- (ratio) - numerical with a real 0 (0 means nothing)

We need to make sure the datatype is string, integer, or float

In [9]:
def changen_tofloat(array_data, df):
    for x in array_data:
        y = df[x]  
        l = 0
        u = []
        for i in range(0, len(y)):
            z = y[i]    
            if z != '?':
                w = float(z)
                u.append(w)
            else:
                u.append(np.nan)
                l = l+1
        df[x] = u
        df_count[x][1] = l

# Question 5: Call the changen_tofloat function for the float_names
display the first 40 values

In [20]:
changen_tofloat(float_names, chronic_kidney_disease)
chronic_kidney_disease[float_names][0:40]

    serum creatinine  potassium  hemoglobin
0                1.2        NaN        15.4
1                0.8        NaN        11.3
2                1.8        NaN         9.6
3                3.8        2.5        11.2
4                1.4        NaN        11.6
5                1.1        3.2        12.2
6               24.0        4.0        12.4
7                1.1        NaN        12.4
8                1.9        NaN        10.8
9                7.2        3.7         9.5
10               4.0        NaN         9.4
11               2.7        4.2        10.8
12               2.1        5.8         9.7
13               4.6        3.4         9.8
14               4.1        6.4         5.6
15               9.6        4.9         7.6
16               2.2        4.1        12.6
17               5.2        3.7        12.1
18               1.3        4.3        12.7
19               1.6        NaN        10.3
20               3.9        5.2         7.7
21              76.0        NaN        10.9
22               7.7        3.8         9.8
23               NaN        NaN         NaN
24               1.4        4.0        11.1
25               1.9        5.2         9.9
26               2.4        3.4        11.6
27               2.7        4.0        12.5
28               1.4        NaN         NaN
29               1.4        NaN        12.9
30               7.3        4.9         NaN
31               1.5        4.6        10.1
32               1.5        4.9        11.3
33               2.5        NaN        10.1
34               5.2        NaN         NaN
35               2.0        NaN        12.0
36               1.8        3.9        10.3
37               3.4        4.7         9.7
38               4.1        5.9        12.5
39               3.4        4.2        13.0

# Changen_toint function to change string to integer

In [14]:
# Make sure you run this function only once otherwise; an error will occur
def changen_toint(array_data, df):
    for x in array_data:
        y = df[x]    
        u = []        
        for i in range(0, len(y)):
            z = y[i] 
            
            if z != '?':
                if z.find('.') == -1:
                    w = int(z)              
                    u.append(w)
                else:
                    u.append(pd.NA)
            else:
                    u.append(pd.NA)
                
           
        df[x] = u

## Question 6: Call the changen_toint function to change string to integers and 
display first 40 values

In [30]:
changen_toint(integer_names, chronic_kidney_disease)
chronic_kidney_disease[integer_names][0:40]

,age,blood pressure,blood glucose random,blood urea,sodium,packed cell volume,white blood cell count
0,48,80,121,36,<NA>,44,7800
1,7,50,<NA>,18,<NA>,38,6000
2,62,80,423,53,<NA>,31,7500
3,48,70,117,56,111,32,6700
4,51,80,106,26,<NA>,35,7300
5,60,90,74,25,142,39,7800
6,68,70,100,54,104,36,<NA>
7,24,<NA>,410,31,<NA>,44,6900
8,52,100,138,60,<NA>,33,9600
9,53,90,70,107,114,29,12100
10,50,60,490,55,<NA>,28,<NA>
11,63,70,380,60,131,32,4500
12,68,70,208,72,138,28,12200
13,68,70,98,86,135,<NA>,<NA>
14,68,80,157,90,130,16,11000
15,40,80,76,162,141,24,3800
16,47,70,99,46,138,<NA>,<NA>
17,47,80,114,87,139,<NA>,<NA>
18,60,100,263,27,135,37,11400
19,62,60,100,31,<NA>,30,5300
20,61,80,173,148,135,24,9200
21,60,90,<NA>,180,<NA>,32,6200
22,48,80,95,163,136,32,6900
23,21,70,<NA>,<NA>,<NA>,<NA>,<NA>
24,42,100,<NA>,50,129,39,8300
25,61,60,108,75,141,29,8400
26,75,80,156,45,140,35,10300
27,69,70,264,87,130,37,9600
28,75,70,123,31,<NA>,<NA>,<NA>
29,68,70,<NA>,28,<NA>,38,<NA>
30,<NA>,70,93,155,132,<NA>,<NA>
31,73,90,107,33,141,30,7800
32,61,90,159,39,133,34,9600
33,60,100,140,55,<NA>,29,<NA>
34,70,70,171,153,<NA>,<NA>,<NA>
35,65,90,270,39,<NA>,36,9800
36,76,70,92,29,133,32,<NA>
37,72,80,137,65,141,28,6900
38,69,80,<NA>,103,132,<NA>,<NA>
39,82,80,140,70,136,40,9800

# Function to change object to strings and put np.nan for missing values

In [31]:
def changen_tostring(array_data, df):
    for x in array_data:
        y = df[x] 
        
        u = []
        for i in range(0, len(y)):
            z = y[i] 
            
            if z != '?':
                w = str(z)
                u.append(z)
            else:
                u.append(np.nan)
        df[x] = u

# Question 7: Call the changen_tostring function and 
display the first 40 values

In [32]:
changen_tostring(string_names, chronic_kidney_disease)
chronic_kidney_disease[string_names][0:40]

,albumin,sugar,red blood cells,pus cell,pus cell clumps,hypertension,diabetes mellitus,coronary artery disease,appetite,pedal edema,anemia,class
0,1,0,NaN,normal,notpresent,yes,yes,no,good,no,no,ckd
1,4,0,NaN,normal,notpresent,no,no,no,good,no,no,ckd
2,2,3,normal,normal,notpresent,no,yes,no,poor,no,yes,ckd
3,4,0,normal,abnormal,present,yes,no,no,poor,yes,yes,ckd
4,2,0,normal,normal,notpresent,no,no,no,good,no,no,ckd
5,3,0,NaN,NaN,notpresent,yes,yes,no,good,yes,no,ckd
6,0,0,NaN,normal,notpresent,no,no,no,good,no,no,ckd
7,2,4,normal,abnormal,notpresent,no,yes,no,good,yes,no,ckd
8,3,0,normal,abnormal,present,yes,yes,no,good,no,yes,ckd
9,2,0,abnormal,abnormal,present,yes,yes,no,poor,no,yes,ckd
10,2,4,NaN,abnormal,present,yes,yes,no,good,no,yes,ckd
11,3,0,abnormal,abnormal,present,yes,yes,no,poor,yes,no,ckd
12,3,1,NaN,normal,present,yes,yes,yes,poor,yes,no,ckd
13,NaN,NaN,NaN,NaN,notpresent,yes,yes,yes,poor,yes,no,ckd
14,3,2,normal,abnormal,present,yes,yes,yes,poor,yes,no,ckd
15,3,0,NaN,normal,notpresent,yes,no,no,good,no,yes,ckd
16,2,0,NaN,normal,notpresent,no,no,no,good,no,no,ckd
17,NaN,NaN,NaN,NaN,notpresent,yes,no,no,poor,no,no,ckd
18,0,3,NaN,normal,notpresent,yes,yes,yes,good,no,no,ckd
19,1,0,NaN,abnormal,present,yes,no,yes,good,no,no,ckd
20,2,0,abnormal,abnormal,notpresent,yes,yes,yes,poor,yes,yes,ckd
21,NaN,NaN,NaN,NaN,notpresent,yes,yes,yes,good,no,no,ckd
22,4,0,normal,abnormal,notpresent,yes,no,no,good,no,yes,ckd
23,0,0,NaN,normal,notpresent,no,no,no,poor,no,yes,ckd
24,4,0,normal,abnormal,notpresent,yes,no,no,poor,no,no,ckd
25,0,0,NaN,normal,notpresent,yes,yes,no,good,no,yes,ckd
26,0,0,NaN,normal,notpresent,yes,yes,no,poor,no,no,ckd
27,3,4,normal,abnormal,notpresent,yes,yes,yes,good,yes,no,ckd
28,1,3,NaN,NaN,notpresent,no,yes,no,good,no,no,ckd
29,1,0,abnormal,abnormal,present,no,no,yes,good,no,no,ckd
30,NaN,NaN,NaN,NaN,notpresent,yes,yes,no,good,no,no,ckd
31,3,0,NaN,abnormal,present,no,no,no,poor,no,no,ckd
32,1,1,NaN,normal,notpresent,yes,yes,no,poor,no,no,ckd
33,2,0,abnormal,abnormal,notpresent,yes,no,no,poor,no,no,ckd
34,1,0,normal,NaN,present,no,yes,no,poor,no,no,ckd
35,2,1,abnormal,normal,notpresent,yes,yes,no,poor,no,yes,ckd
36,1,0,normal,normal,notpresent,yes,no,no,good,no,no,ckd
37,NaN,NaN,NaN,NaN,notpresent,yes,yes,no,poor,no,yes,ckd
38,3,0,abnormal,normal,notpresent,yes,no,no,good,no,no,ckd
39,2,2,normal,NaN,notpresent,yes,yes,no,good,no,no,ckd

## the info method gives you information about the dataset
- There are missing values nan indicates a missing value
- Also notice the type of data that python has set each variables
- Age has 400 - 391 = 9 missing values
- blood_pressure has 400 - 388 = 12 missing values
- specific_gravity has 400 - 353 = 47 missing values

In [33]:
chronic_kidney_disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       400 non-null    int64
 1   age                      391 non-null    object
 2   blood pressure           388 non-null    object
 3   specific gravity         400 non-null    object
 4   albumin                  354 non-null    object
 5   sugar                    351 non-null    object
 6   red blood cells          248 non-null    object
 7   pus cell                 335 non-null    object
 8   pus cell clumps          396 non-null    object
 9   bacteria                 400 non-null    object
 10  blood glucose random     356 non-null    object
 11  blood urea               378 non-null    object
 12  serum creatinine         400 non-null    object
 13  sodium                   312 non-null    object
 14  potassium                400 non-null    object
 15  hemoglobin               400 non-null    object
 16  packed cell volume       329 non-null    object
 17  white blood cell count   294 non-null    object
 18  red blood cell count     400 non-null    object
 19  hypertension             398 non-null    object
 20  diabetes mellitus        398 non-null    object
 21  coronary artery disease  398 non-null    object
 22  appetite                 399 non-null    object
 23  pedal edema              399 non-null    object
 24  anemia                   399 non-null    object
 25  class                    400 non-null    object
dtypes: int64(1), object(25)
memory usage: 81.4+ KB

# Question 8: Determine the missing values for each variable based on the values above. Create an array called no_of_missing_values and list the number of missing values starting from variable age to anemia.

In [ ]:
no_of_missing_values = ...

In [ ]:
#Vanessa Rocha code
columns_to_check = chronic_kidney_disease.columns[1:24]
no_of_missing_values = (chronic_kidney_disease[columns_to_check] == '?').sum().values
no_of_missing_values

In [61]:
all_names = make_array("age", "blood pressure", "specific gravity","albumin", "sugar", "red blood cells", "pus cell", "pus cell clumps", "bacteria", 
                       "blood glucose random", "blood urea", "serum creatinine", "sodium", "potassium", "hemoglobin",
                      "packed cell volume", "white blood cell count", "red blood cell count", "hypertension",
                      "diabetes mellitus", "coronary artery disease", "appetite", "pedal edema", "anemia", "class")

missing_v = Table().with_column("Field", all_names)
missing_v


def missing_values(kidney_disease, all_names, missing_v):
    u =[]
    for x in all_names:
        s = kidney_disease.where(x, are.equal_to('?')).column(x)
        t = len(s)
        u.append(t)
    missing_v['Total Missing'] = u
    missing_v.show()
        
        
        
missing_values(kidney_disease, all_names, missing_v)

Missing Values